---
title: "COVID_scraping"
author: "Michał Michalak"
date: "04.04.2020"
output: html_document
---

```{r}
library(DCluster)
```

```{r}
library(INLA)
```

```{r}
library(ggiraph)
```

```{r}
library(plotly)
```

```{r}
library(reshape2)
```

```{r}
library("robotstxt")
```

```{r}
paths_allowed("https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2")
```

```{r}
library(rvest)
```

```{r}
library(SpatialEpiApp)
```

```{r}
library(foreign)
```

```{r}
library(devtools)
```

```{r}
library(sf)
```

```{r}
library(tmap)
```

```{r}
library(rgdal)
```

```{r}
library(maps)
```

```{r}
library(maptools)
```

```{r}
library(sp)
```

```{r}
library(stringr)
```

```{r}
library(webshot)
```

```{r}
library(RCurl)
```

```{r}
library(magick)
```

```{r}
library(splashr)
```

```{r}
library(RSelenium)
```

```{r}
library(tidyverse)
```

```{r}
library(V8)
```

```{r}
library(rvest)
```

```{r}
library(stringr)
```

```{r}
library(plyr)
```

```{r}
library(dplyr)
```

```{r}
library(ggvis)
```

```{r}
library(knitr)
```

```{r}
library(XML)
```

```{r}
library(methods)
```

```{r}
setwd<-getwd()
```

```{r}
shell('docker ps')
Sys.sleep(5)
```

```{r}
remDr <- remoteDriver(remoteServerAddr = "192.168.99.100", port = 4445L, browserName = "chrome")
Sys.sleep(5)
```

```{r}
shell('docker run -d -p 4445:4444 selenium/standalone-chrome')
Sys.sleep(5)
```

```{r}
remDr <- remoteDriver(remoteServerAddr = "192.168.99.100", port = 4445L, browserName = "chrome")
Sys.sleep(5)
```

```{r}
remDr$open()
Sys.sleep(5)
```

```{r}
remDr$navigate("https://www.gov.pl/web/koronawirus/wykaz-zarazen-koronawirusem-sars-cov-2")
Sys.sleep(2)
```

```{r}
webel2<- remDr$findElement(using = "css selector", "#js-pagination-rows > a:nth-child(3)")
Sys.sleep(2)
```

```{r}
webel2$sendKeysToElement(list(key="enter"))
Sys.sleep(2)
```

```{r}
wojewodztwo <- c("dolnośląskie", "kujawsko-pomorskie", "lubelskie", "lubuskie", "łódzkie", "małopolskie", "mazowieckie", "opolskie", "podkarpackie", "podlaskie", "pomorskie", "śląskie", "świętokrzyskie", "warmińsko-mazurskie", "wielkopolskie", "zachodniopomorskie")
```

```{r}
tableElem <- remDr$findElement(using = "css selector", value= "table" )
Sys.sleep(2)
```

```{r}
tekst <- tableElem$getElementText()
```

```{r}
tekst
```

```{r}
przypadki_obserwowane <-str_extract_all(tekst, "[a-z]+ [0-9]+")[[1]]
```

```{r}
przypadki_obserwowane
```

```{r}
przypadki_obserwowane <-str_extract_all(przypadki_obserwowane, "[0-9]+")[]
```

```{r}
przypadki_obserwowane <- as.numeric(przypadki_obserwowane)
```

<area id><date><population><cases>
```{r}
kod <- c(02, 04, 06, 08, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32)
```

```{r}
ludnosc <- c(2865000, 2060000, 2148000, 1004000, 2466000, 3349000, 5385000, 948808, 2129000, 1193000, 
             2295000, 4501000, 1263000, 1408000, 3466000, 1679000 )
```

```{r}
czas <- (as.POSIXlt(Sys.time()))
```

```{r}
czas<- as.character(czas,usetz=TRUE)
```

```{r}
czas <- rep(czas, 16)
```

```{r}
combined <- data.frame(wojewodztwo, kod, ludnosc, czas, przypadki_obserwowane)
``` 

```{r}
ratio <- sum(combined$przypadki_obserwowane)/sum(combined$ludnosc)
```

```{r}
przypadki_oczekiwane<-(combined$ludnosc)*ratio
```

```{r}
combined<-dplyr::mutate(combined, przypadki_oczekiwane)
```

```{r}
Obserwowane100<-(combined$przypadki_obserwowane/combined$ludnosc)*100000
```

```{r}
combined<-dplyr::mutate(combined, Obserwowane100)
```

```{r}
SMR<-combined$przypadki_obserwowane/combined$przypadki_oczekiwane
```

```{r}
combined<-dplyr::mutate(combined, SMR)
```

```{r}
combined
```

```{r}
combined$wojewodztwo
```

```{r}
mapaw <- st_read("Województwa.shp")
```

```{r}
mapaw$JPT_NAZWA_
```

```{r}
riskvec<- c( combined$SMR[12],
             combined$SMR[8], 
             combined$SMR[15], 
             combined$SMR[16], 
             combined$SMR[13], 
             combined$SMR[2], 
             combined$SMR[10], 
             combined$SMR[1], 
             combined$SMR[9], 
             combined$SMR[6], 
             combined$SMR[11], 
             combined$SMR[14], 
             combined$SMR[5], 
             combined$SMR[7], 
             combined$SMR[3], 
             combined$SMR[4] )
```

```{r}
mapaw$RelativeRisk <- riskvec
```

```{r}
mapaw$RelativeRounded<-as.character(round(mapaw$RelativeRisk, 2))
```

```{r}
combined <- dplyr::mutate(combined, czas)
```

```{r}
write.table(combined, file="data2_.csv", sep=";", dec = ".", row.names = FALSE)
```

